#!/usr/bin/env node
/**
 * build-catalog.mjs
 * Auto-generates CATALOG.md from all skills/\/**\/**\/SKILL.md files.
 * Groups skills by role (category) and marks mutation flag.
 */

import { readFileSync, writeFileSync } from 'fs';
import { glob } from 'glob';
import matter from 'gray-matter';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const CATEGORY_ORDER = [
  'merchandising',
  'order-management',
  'customer-ops',
  'customer-support',
  'marketing',
  'finance',
  'store-management',
  'analytics',
];

const MUTATION_METHODS = ['POST', 'PUT', 'PATCH', 'DELETE'];

function isMutating(endpoints) {
  if (!Array.isArray(endpoints)) return false;
  return endpoints.some((ep) =>
    MUTATION_METHODS.some((method) => ep.trim().startsWith(method))
  );
}

async function main() {
  const skillFiles = await glob('skills/**/**/SKILL.md', { cwd: ROOT });

  const byCategory = {};
  for (const cat of CATEGORY_ORDER) byCategory[cat] = [];

  for (const relPath of skillFiles.sort()) {
    const filePath = path.join(ROOT, relPath);
    const raw = readFileSync(filePath, 'utf8');
    const { data: fm } = matter(raw);

    if (!fm.role || !byCategory[fm.role]) continue;

    byCategory[fm.role].push({
      name: fm.name || '(unnamed)',
      description: fm.description || '',
      endpoints: fm.rest_endpoints || [],
      mutating: isMutating(fm.rest_endpoints),
      path: relPath,
    });
  }

  const totalSkills = Object.values(byCategory).flat().length;
  const now = new Date().toISOString().split('T')[0];

  const lines = [
    '# WooCommerce AI Skills — Catalog',
    '',
    `> Auto-generated on ${now} · ${totalSkills} skills · 8 categories`,
    '',
    '---',
    '',
  ];

  for (const cat of CATEGORY_ORDER) {
    const skills = byCategory[cat];
    if (skills.length === 0) continue;

    lines.push(`## ${cat}/ (${skills.length} skills)`);
    lines.push('');
    lines.push('| Skill | Description | Mutations? |');
    lines.push('|-------|-------------|------------|');

    for (const skill of skills) {
      const mutation = skill.mutating ? '✏️ Yes' : '👁️ Read-only';
      lines.push(`| \`${skill.name}\` | ${skill.description} | ${mutation} |`);
    }

    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by `pnpm build:catalog`. Do not edit manually.*');
  lines.push('');

  const output = lines.join('\n');
  const catalogPath = path.join(ROOT, 'CATALOG.md');
  writeFileSync(catalogPath, output, 'utf8');

  console.log(`✅ CATALOG.md written — ${totalSkills} skills across ${CATEGORY_ORDER.length} categories`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
